// Des textes pour apprendre à comprendre, écrits pour Maitrize.
//
// Programme de français du cycle 2 (2024), « Comprendre un texte » : un texte
// narratif, informatif ou prescriptif d'une dizaine de lignes au CP, d'une
// quinzaine au CE1, d'une vingtaine au CE2 — et, au CE2, poétique ou
// théâtral ; dégager le sens global ; les mots inconnus ; se repérer dans la
// chaîne anaphorique, qui relie un nom à ses reprises ; l'implicite, les
// inférences ; justifier ses réponses par un retour au texte. Chaque texte
// porte ses questions, leur réponse et la ligne qui la justifie, ses
// reprises — le mot, sa ligne, ce qu'il désigne — et un mot à élucider.

export type Classe = "CP" | "CE1" | "CE2";
export type TypeDeTexte = "narratif" | "informatif" | "prescriptif" | "poétique" | "théâtral";
export type TypeDeQuestion = "littérale" | "inférence" | "reprise" | "vocabulaire";

export interface Question { q: string; r: string; type: TypeDeQuestion; ligne?: number }
export interface Reprise { mot: string; ligne: number; designe: string }
export interface TexteAComprendre {
  id: string;
  classe: Classe;
  type: TypeDeTexte;
  titre: string;
  /** Le texte, ligne par ligne : on numérote les lignes pour y revenir ; une ligne vide sépare les strophes et ne compte pas. */
  lignes: string[];
  questions: Question[];
  /** Les reprises de la chaîne anaphorique : un pronom ou un autre nom, sa ligne, ce qu'il désigne. */
  reprises: Reprise[];
  /** Trois résumés : le premier est le bon ; les autres mêlent des détails du texte et des erreurs. */
  resumes: string[];
  /** Les grands moments d'un récit, dans l'ordre. */
  moments?: string[];
  /** Ce que ressent un personnage à une ligne du récit, et l'indice qui le montre. */
  emotions?: { qui: string; ligne: number; emotion: string; indice: string }[];
  /** Un mot à élucider par le contexte, son sens, l'indice qui le donne et deux sens qui ne conviennent pas. */
  motInconnu: { mot: string; ligne: number; sens: string; indice: string; leurres: string[] };
}

const T = (t: TexteAComprendre) => t;

export const TEXTES: TexteAComprendre[] = [
  // ── CP : une dizaine de lignes ─────────────────────────────────────────
  T({
    id: "chaton", classe: "CP", type: "narratif", titre: "Le chaton perdu",
    lignes: [
      "Ce matin, Lila entend un petit bruit",
      "derrière la porte du jardin.",
      "Elle ouvre doucement la porte.",
      "Un chaton gris est assis sur le tapis.",
      "Il tremble et il miaule très fort.",
      "Lila le prend dans ses bras.",
      "« Tu as froid, mon petit », dit-elle.",
      "Elle lui donne un bol de lait.",
      "Le chaton boit tout le lait.",
      "Puis il s'endort sur les genoux de Lila.",
    ],
    questions: [
      { q: "Qui entend un petit bruit ?", r: "Lila.", type: "littérale", ligne: 1 },
      { q: "Qui est « il » à la ligne 5 ?", r: "Le chaton gris.", type: "reprise", ligne: 5 },
      { q: "Pourquoi le chaton tremble-t-il ?", r: "Il a froid ; il est perdu.", type: "inférence", ligne: 7 },
      { q: "Que donne Lila au chaton ?", r: "Un bol de lait.", type: "littérale", ligne: 8 },
      { q: "Le chaton a-t-il encore peur à la fin ? Comment le sais-tu ?", r: "Non : il s'endort sur les genoux de Lila.", type: "inférence", ligne: 10 },
    ],
    reprises: [{ mot: "Elle", ligne: 3, designe: "Lila" }, { mot: "Il", ligne: 5, designe: "le chaton" }, { mot: "le", ligne: 6, designe: "le chaton" }, { mot: "lui", ligne: 8, designe: "le chaton" }],
    resumes: ["Lila trouve un chaton qui a froid derrière la porte ; elle le réchauffe et lui donne du lait.", "Lila perd son chaton dans le jardin et le cherche partout.", "Un chaton gris boit le lait de Lila, puis il s'enfuit dans le jardin."],
    moments: ["Lila entend un petit bruit derrière la porte.", "Elle trouve un chaton gris qui tremble.", "Elle lui donne un bol de lait.", "Le chaton s'endort sur ses genoux."],
    emotions: [{ qui: "le chaton", ligne: 5, emotion: "il a peur et il a froid", indice: "Il tremble et il miaule très fort." }, { qui: "le chaton", ligne: 10, emotion: "il est rassuré, il se sent bien", indice: "il s'endort sur les genoux de Lila" }],
    motInconnu: { mot: "tremble", ligne: 5, sens: "bouge tout seul, à petits coups, parce qu'il a froid ou peur", indice: "Lila dit : « Tu as froid ».", leurres: ["court très vite", "dort profondément"] },
  }),
  T({
    id: "cabane", classe: "CP", type: "narratif", titre: "La cabane",
    lignes: [
      "Tom et Sami veulent faire une cabane.",
      "Ils ramassent des branches dans le bois.",
      "Sami apporte une vieille couverture.",
      "Les deux amis la posent sur les branches.",
      "La cabane est prête !",
      "Mais le ciel devient tout noir.",
      "Vite, les garçons entrent dans la cabane.",
      "Ploc, ploc, ploc… Ils entendent les gouttes.",
      "Ils restent bien au sec.",
      "« Notre cabane est la meilleure ! » dit Tom.",
    ],
    questions: [
      { q: "Que veulent faire Tom et Sami ?", r: "Une cabane.", type: "littérale", ligne: 1 },
      { q: "Avec quoi font-ils la cabane ?", r: "Avec des branches et une vieille couverture.", type: "littérale", ligne: 3 },
      { q: "Que désigne « la » à la ligne 4 ?", r: "La vieille couverture.", type: "reprise", ligne: 4 },
      { q: "Quel temps fait-il à la fin ? Quels mots te le disent ?", r: "Il pleut : « le ciel devient tout noir », « les gouttes ».", type: "inférence", ligne: 8 },
      { q: "Pourquoi Tom dit-il que leur cabane est la meilleure ?", r: "Parce qu'ils sont restés au sec sous la pluie.", type: "inférence", ligne: 9 },
    ],
    reprises: [{ mot: "Ils", ligne: 2, designe: "Tom et Sami" }, { mot: "Les deux amis", ligne: 4, designe: "Tom et Sami" }, { mot: "la", ligne: 4, designe: "la couverture" }, { mot: "les garçons", ligne: 7, designe: "Tom et Sami" }],
    resumes: ["Tom et Sami construisent une cabane ; quand la pluie arrive, ils restent au sec dedans.", "Tom et Sami jouent dans le bois, mais la pluie détruit leur cabane.", "Sami apporte une couverture pour dormir dans le jardin avec Tom."],
    moments: ["Tom et Sami ramassent des branches.", "Ils posent une couverture sur les branches.", "Le ciel devient tout noir.", "Ils restent au sec dans la cabane."],
    emotions: [{ qui: "Tom et Sami", ligne: 5, emotion: "ils sont contents de leur travail", indice: "La cabane est prête !" }, { qui: "Tom", ligne: 10, emotion: "il est fier", indice: "« Notre cabane est la meilleure ! »" }],
    motInconnu: { mot: "au sec", ligne: 9, sens: "sans être mouillés", indice: "Ils sont dans la cabane pendant qu'il pleut.", leurres: ["tout mouillés", "dans le noir"] },
  }),
  T({
    id: "herisson", classe: "CP", type: "informatif", titre: "Le hérisson",
    lignes: [
      "Le hérisson est un petit animal.",
      "Il vit dans les jardins et dans les bois.",
      "Son dos est couvert de piquants.",
      "Quand il a peur, il se roule en boule.",
      "Les piquants le protègent.",
      "Le hérisson sort surtout la nuit.",
      "Il mange des vers, des limaces et des insectes.",
      "En hiver, il dort dans un nid de feuilles.",
      "Il ne se réveille qu'au printemps.",
      "C'est un ami des jardiniers.",
    ],
    questions: [
      { q: "Où vit le hérisson ?", r: "Dans les jardins et dans les bois.", type: "littérale", ligne: 2 },
      { q: "Que fait le hérisson quand il a peur ?", r: "Il se roule en boule.", type: "littérale", ligne: 4 },
      { q: "Qui est « il » à la ligne 7 ?", r: "Le hérisson.", type: "reprise", ligne: 7 },
      { q: "Que fait le hérisson en hiver ?", r: "Il dort dans un nid de feuilles.", type: "littérale", ligne: 8 },
      { q: "Pourquoi est-il un ami des jardiniers ?", r: "Il mange les limaces et les insectes qui abîment les plantes.", type: "inférence", ligne: 7 },
    ],
    reprises: [{ mot: "Il", ligne: 2, designe: "le hérisson" }, { mot: "Son", ligne: 3, designe: "le hérisson" }, { mot: "le", ligne: 5, designe: "le hérisson" }],
    resumes: ["Ce texte explique comment vit le hérisson : où il habite, ce qu'il mange, comment il se protège.", "Ce texte raconte l'histoire d'un hérisson qui se perd dans un jardin.", "Ce texte explique comment fabriquer un nid pour un hérisson."],
    motInconnu: { mot: "piquants", ligne: 3, sens: "des sortes de petites épines pointues", indice: "Ils le protègent quand il se roule en boule.", leurres: ["des poils tout doux", "des plumes"] },
  }),
  T({
    id: "salade", classe: "CP", type: "prescriptif", titre: "La salade de fruits",
    lignes: [
      "Pour quatre enfants, il faut :",
      "deux pommes, deux bananes,",
      "une orange et un peu de jus de citron.",
      "1. Demande à un adulte d'éplucher les fruits.",
      "2. Coupe les fruits en petits morceaux.",
      "3. Mets les morceaux dans un saladier.",
      "4. Verse le jus de citron dessus.",
      "5. Mélange doucement avec une cuillère.",
      "6. Mets le saladier au frais une heure.",
      "Bon appétit !",
    ],
    questions: [
      { q: "Qu'est-ce que ce texte apprend à faire ?", r: "Une salade de fruits.", type: "inférence" },
      { q: "Combien de bananes faut-il ?", r: "Deux.", type: "littérale", ligne: 2 },
      { q: "Que fait-on juste après avoir coupé les fruits ?", r: "On les met dans un saladier.", type: "littérale", ligne: 6 },
      { q: "Pourquoi les phrases ont-elles des numéros ?", r: "Pour faire les étapes dans l'ordre.", type: "inférence" },
      { q: "Que désigne « dessus » à la ligne 7 ?", r: "Les morceaux de fruits, dans le saladier.", type: "reprise", ligne: 7 },
      { q: "Où met-on le saladier à la fin ?", r: "Au frais, une heure.", type: "littérale", ligne: 9 },
    ],
    reprises: [{ mot: "dessus", ligne: 7, designe: "les morceaux de fruits" }],
    resumes: ["Ce texte explique comment préparer une salade de fruits.", "Ce texte raconte le goûter de quatre enfants.", "Ce texte explique comment faire pousser des pommes et des oranges."],
    motInconnu: { mot: "saladier", ligne: 6, sens: "un grand bol où l'on prépare la salade", indice: "On y met les morceaux, puis on mélange.", leurres: ["une petite cuillère", "un couteau pour éplucher"] },
  }),
  T({
    id: "escargot", classe: "CP", type: "narratif", titre: "Le petit escargot",
    lignes: [
      "Un petit escargot veut voir la mer.",
      "Il part un matin, tout doucement.",
      "Il traverse le jardin.",
      "Il passe sous la haie.",
      "Il monte sur un gros caillou.",
      "Le soir, il est très fatigué.",
      "Une coccinelle se pose près de lui.",
      "« Où vas-tu ? » demande-t-elle.",
      "« Je vais voir la mer ! » répond l'escargot.",
      "La coccinelle rit : « La mer est très loin ! »",
    ],
    questions: [
      { q: "Que veut faire le petit escargot ?", r: "Voir la mer.", type: "littérale", ligne: 1 },
      { q: "Par où passe-t-il ?", r: "Le jardin, sous la haie, sur un gros caillou.", type: "littérale", ligne: 3 },
      { q: "Qui est « elle » à la ligne 8 ?", r: "La coccinelle.", type: "reprise", ligne: 8 },
      { q: "Pourquoi la coccinelle rit-elle ?", r: "L'escargot va très lentement et la mer est très loin : il n'arrivera pas vite.", type: "inférence", ligne: 10 },
      { q: "Pourquoi l'escargot est-il fatigué ?", r: "Il a marché toute la journée.", type: "inférence", ligne: 6 },
    ],
    reprises: [{ mot: "Il", ligne: 2, designe: "le petit escargot" }, { mot: "lui", ligne: 7, designe: "l'escargot" }, { mot: "elle", ligne: 8, designe: "la coccinelle" }],
    resumes: ["Un petit escargot part voir la mer, mais il va si lentement que la coccinelle se moque de lui.", "Un petit escargot va voir la mer avec une coccinelle.", "Une coccinelle se perd dans le jardin et rencontre un escargot fatigué."],
    moments: ["Le petit escargot part voir la mer.", "Il traverse le jardin et passe sous la haie.", "Le soir, il est très fatigué.", "La coccinelle rit : la mer est très loin."],
    emotions: [{ qui: "le petit escargot", ligne: 9, emotion: "il est content, plein d'espoir", indice: "« Je vais voir la mer ! »" }, { qui: "la coccinelle", ligne: 10, emotion: "elle s'amuse, elle trouve ça drôle", indice: "La coccinelle rit" }],
    motInconnu: { mot: "haie", ligne: 4, sens: "une rangée d'arbustes qui fait comme un mur de feuilles", indice: "L'escargot passe dessous, au bord du jardin.", leurres: ["une flaque d'eau", "un grand chemin"] },
  }),
  T({
    id: "beret", classe: "CP", type: "prescriptif", titre: "Le jeu du béret",
    lignes: [
      "Il faut deux équipes et un foulard.",
      "Chaque équipe se met sur une ligne.",
      "Le foulard est posé au milieu.",
      "Dans chaque équipe, chaque enfant a un numéro.",
      "Le maître appelle un numéro.",
      "Les deux enfants qui ont ce numéro courent.",
      "Il faut prendre le foulard",
      "et revenir dans son camp sans être touché.",
      "L'équipe qui gagne marque un point.",
      "On joue jusqu'à dix points.",
    ],
    questions: [
      { q: "De quoi a-t-on besoin pour jouer ?", r: "De deux équipes et d'un foulard.", type: "littérale", ligne: 1 },
      { q: "Où est posé le foulard ?", r: "Au milieu.", type: "littérale", ligne: 3 },
      { q: "Qui court quand le maître appelle un numéro ?", r: "Les deux enfants qui ont ce numéro.", type: "littérale", ligne: 6 },
      { q: "Que désigne « ce numéro » à la ligne 6 ?", r: "Le numéro que le maître a appelé.", type: "reprise", ligne: 6 },
      { q: "Que se passe-t-il si l'enfant est touché avant d'arriver dans son camp ?", r: "Il ne gagne pas le point.", type: "inférence", ligne: 8 },
      { q: "Quand le jeu s'arrête-t-il ?", r: "Quand une équipe a dix points.", type: "inférence", ligne: 10 },
    ],
    reprises: [{ mot: "ce numéro", ligne: 6, designe: "le numéro appelé par le maître" }],
    resumes: ["Ce texte explique les règles du jeu du béret.", "Ce texte raconte une partie de foulard dans la cour.", "Ce texte explique comment fabriquer un béret."],
    motInconnu: { mot: "camp", ligne: 8, sens: "l'endroit, la ligne de son équipe", indice: "On y revient après avoir pris le foulard.", leurres: ["la tente où l'on dort", "le foulard"] },
  }),
  T({
    id: "pique-nique", classe: "CP", type: "narratif", titre: "Le pique-nique",
    lignes: [
      "Dimanche, Papi emmène Nina et Léo au parc.",
      "Ils posent une nappe rouge sur l'herbe.",
      "Nina sort les sandwichs et les fruits.",
      "Tout à coup, une fourmi grimpe sur la nappe.",
      "Puis une autre, et encore une autre !",
      "Elles marchent tout droit vers le gâteau.",
      "Léo crie : « Au secours, des fourmis ! »",
      "Papi rit et pose une miette de gâteau dans l'herbe.",
      "Les petites bêtes s'en vont avec la miette.",
      "Le soir, Nina dit : « Les fourmis aussi ont fait un pique-nique ! »",
    ],
    questions: [
      { q: "Où Papi emmène-t-il Nina et Léo ?", r: "Au parc.", type: "littérale", ligne: 1 },
      { q: "Qui est « Elles » à la ligne 6 ?", r: "Les fourmis.", type: "reprise", ligne: 6 },
      { q: "Que veulent manger les fourmis ?", r: "Le gâteau.", type: "littérale", ligne: 6 },
      { q: "Pourquoi Papi pose-t-il une miette dans l'herbe ?", r: "Pour que les fourmis quittent la nappe et laissent le pique-nique.", type: "inférence", ligne: 8 },
      { q: "Pourquoi Nina dit-elle que les fourmis ont fait un pique-nique ?", r: "Elles ont emporté la miette de gâteau pour la manger.", type: "inférence", ligne: 10 },
    ],
    reprises: [{ mot: "Ils", ligne: 2, designe: "Papi, Nina et Léo" }, { mot: "Elles", ligne: 6, designe: "les fourmis" }, { mot: "Les petites bêtes", ligne: 9, designe: "les fourmis" }],
    resumes: ["Pendant un pique-nique, des fourmis arrivent sur la nappe ; Papi les attire ailleurs avec une miette de gâteau.", "Nina et Léo font un pique-nique, mais il se met à pleuvoir.", "Des fourmis mangent tout le gâteau de Papi."],
    moments: ["Papi, Nina et Léo posent une nappe sur l'herbe.", "Des fourmis grimpent sur la nappe.", "Papi pose une miette de gâteau dans l'herbe.", "Les fourmis s'en vont avec la miette."],
    emotions: [{ qui: "Léo", ligne: 7, emotion: "il a peur, il est surpris", indice: "Au secours, des fourmis !" }, { qui: "Papi", ligne: 8, emotion: "il est amusé et calme", indice: "Papi rit" }],
    motInconnu: { mot: "grimpe", ligne: 4, sens: "monte en s'accrochant", indice: "La fourmi arrive de l'herbe et monte sur la nappe.", leurres: ["tombe", "dort"] },
  }),

  // ── CE1 : une quinzaine de lignes ──────────────────────────────────────
  T({
    id: "gouter", classe: "CE1", type: "narratif", titre: "Le goûter disparu",
    lignes: [
      "Ce mercredi, Inès a préparé des crêpes pour le goûter.",
      "Elle les a posées sur la table de la cuisine,",
      "puis elle est allée chercher ses amis dans le jardin.",
      "Quand ils reviennent, l'assiette est vide !",
      "« Qui a mangé nos crêpes ? » s'écrie Inès.",
      "Les enfants cherchent partout.",
      "Sous la table, Noah trouve des miettes.",
      "Près de la porte, Jade voit des traces de pattes",
      "toutes collantes de confiture.",
      "Les traces mènent jusqu'au panier de Biscuit.",
      "Le petit chien dort, le museau plein de sucre.",
      "« Le voleur, c'est lui ! » rit Noah.",
      "Inès n'est pas fâchée très longtemps :",
      "elle sort de nouveau la poêle,",
      "et cette fois, elle ferme bien la porte de la cuisine.",
    ],
    questions: [
      { q: "Qu'a préparé Inès pour le goûter ?", r: "Des crêpes.", type: "littérale", ligne: 1 },
      { q: "Que désigne « les » à la ligne 2 ?", r: "Les crêpes.", type: "reprise", ligne: 2 },
      { q: "Quels indices les enfants trouvent-ils ?", r: "Des miettes, des traces de pattes collantes de confiture.", type: "littérale", ligne: 8 },
      { q: "Qui a mangé les crêpes ? Comment le sait-on ?", r: "Biscuit, le chien : les traces mènent à son panier et il a le museau plein de sucre.", type: "inférence", ligne: 11 },
      { q: "Pourquoi Inès ferme-t-elle la porte à la fin ?", r: "Pour que le chien ne mange pas les nouvelles crêpes.", type: "inférence", ligne: 15 },
      { q: "Que va faire Inès avec la poêle ?", r: "De nouvelles crêpes.", type: "inférence", ligne: 14 },
    ],
    reprises: [{ mot: "Elle", ligne: 2, designe: "Inès" }, { mot: "les", ligne: 2, designe: "les crêpes" }, { mot: "ils", ligne: 4, designe: "Inès et ses amis" }, { mot: "Le petit chien", ligne: 11, designe: "Biscuit" }, { mot: "lui", ligne: 12, designe: "Biscuit" }],
    resumes: ["Le chien Biscuit a mangé les crêpes d'Inès ; les enfants le découvrent grâce aux indices.", "Noah a mangé les crêpes, et Inès est très fâchée contre lui.", "Inès et ses amis cherchent Biscuit, qui s'est perdu dans le jardin."],
    moments: ["Inès prépare des crêpes et va chercher ses amis.", "L'assiette est vide !", "Les enfants trouvent des miettes et des traces de pattes.", "Ils découvrent Biscuit, le museau plein de sucre."],
    emotions: [{ qui: "Inès", ligne: 5, emotion: "elle est surprise et fâchée", indice: "s'écrie Inès" }, { qui: "Inès", ligne: 13, emotion: "elle n'est plus fâchée, elle s'en amuse", indice: "Inès n'est pas fâchée très longtemps" }],
    motInconnu: { mot: "museau", ligne: 11, sens: "le nez et la bouche d'un animal", indice: "C'est le chien qui l'a « plein de sucre ».", leurres: ["la queue d'un animal", "le panier d'un chien"] },
  }),
  T({
    id: "phare", classe: "CE1", type: "narratif", titre: "La lumière du phare",
    lignes: [
      "Au bout de l'île, il y a un vieux phare.",
      "Le gardien s'appelle Marius.",
      "Chaque soir, il monte les cent marches de l'escalier",
      "pour allumer la grande lampe.",
      "Grâce à elle, les bateaux voient les rochers dans la nuit.",
      "Un soir de tempête, la lampe ne s'allume pas.",
      "Marius entend le vent qui siffle et les vagues qui frappent.",
      "Au loin, il aperçoit les feux d'un bateau de pêche.",
      "Le vieil homme ne perd pas de temps.",
      "Il prend sa lanterne et grimpe tout en haut du phare.",
      "Il la balance de droite à gauche, de toutes ses forces.",
      "Le bateau tourne doucement et s'éloigne des rochers.",
      "Le lendemain matin, les pêcheurs viennent frapper à sa porte.",
      "Ils lui apportent un panier de poissons",
      "et un grand merci.",
    ],
    questions: [
      { q: "Comment s'appelle le gardien du phare ?", r: "Marius.", type: "littérale", ligne: 2 },
      { q: "À quoi sert la grande lampe ?", r: "À montrer les rochers aux bateaux dans la nuit.", type: "littérale", ligne: 5 },
      { q: "Qui est « le vieil homme » à la ligne 9 ?", r: "Marius, le gardien.", type: "reprise", ligne: 9 },
      { q: "Que désigne « la » à la ligne 11 ?", r: "La lanterne.", type: "reprise", ligne: 11 },
      { q: "Quel danger court le bateau de pêche ?", r: "Il pourrait se briser sur les rochers.", type: "inférence", ligne: 12 },
      { q: "Pourquoi les pêcheurs apportent-ils un cadeau à Marius ?", r: "Pour le remercier : il les a sauvés.", type: "inférence", ligne: 14 },
    ],
    reprises: [{ mot: "il", ligne: 3, designe: "Marius" }, { mot: "elle", ligne: 5, designe: "la grande lampe" }, { mot: "Le vieil homme", ligne: 9, designe: "Marius" }, { mot: "la", ligne: 11, designe: "la lanterne" }, { mot: "Ils", ligne: 14, designe: "les pêcheurs" }],
    resumes: ["Un soir de tempête, la lampe du phare ne s'allume pas ; Marius sauve un bateau avec sa lanterne.", "Marius part en bateau pendant la tempête pour aider les pêcheurs.", "Les pêcheurs réparent la lampe du phare pour remercier Marius."],
    moments: ["Chaque soir, Marius allume la grande lampe du phare.", "Un soir de tempête, la lampe ne s'allume pas.", "Marius balance sa lanterne en haut du phare.", "Les pêcheurs le remercient avec un panier de poissons."],
    emotions: [{ qui: "Marius", ligne: 9, emotion: "il a peur pour les pêcheurs, il se dépêche", indice: "Le vieil homme ne perd pas de temps." }, { qui: "les pêcheurs", ligne: 15, emotion: "ils sont reconnaissants", indice: "un grand merci" }],
    motInconnu: { mot: "aperçoit", ligne: 8, sens: "voit, de loin et pendant peu de temps", indice: "« Au loin », les feux du bateau.", leurres: ["entend", "touche"] },
  }),
  T({
    id: "abeille", classe: "CE1", type: "informatif", titre: "La vie des abeilles",
    lignes: [
      "Les abeilles vivent ensemble dans une ruche.",
      "Une ruche peut abriter plusieurs milliers d'abeilles.",
      "Chacune a son travail.",
      "La reine est la plus grande : elle pond les œufs.",
      "Les ouvrières sont les plus nombreuses.",
      "Elles nettoient la ruche, nourrissent les larves",
      "et vont chercher le nectar des fleurs.",
      "Avec ce nectar, elles fabriquent le miel.",
      "Les abeilles transportent aussi le pollen d'une fleur à l'autre.",
      "Grâce à elles, les fleurs donnent des fruits.",
      "Une abeille ne pique que si elle a peur :",
      "elle se sent attaquée.",
      "Pour communiquer, les abeilles dansent !",
      "Leur danse indique aux autres où trouver des fleurs.",
      "Sans les abeilles, nous aurions beaucoup moins de fruits.",
    ],
    questions: [
      { q: "Où vivent les abeilles ?", r: "Dans une ruche.", type: "littérale", ligne: 1 },
      { q: "Quel est le travail de la reine ?", r: "Elle pond les œufs.", type: "littérale", ligne: 4 },
      { q: "Qui est « elles » à la ligne 6 ?", r: "Les ouvrières.", type: "reprise", ligne: 6 },
      { q: "Avec quoi les abeilles fabriquent-elles le miel ?", r: "Avec le nectar des fleurs.", type: "littérale", ligne: 8 },
      { q: "Pourquoi aurions-nous moins de fruits sans les abeilles ?", r: "Elles transportent le pollen, et c'est grâce à lui que les fleurs donnent des fruits.", type: "inférence", ligne: 10 },
      { q: "À quoi sert la danse des abeilles ?", r: "À montrer aux autres où trouver des fleurs.", type: "littérale", ligne: 14 },
    ],
    reprises: [{ mot: "Chacune", ligne: 3, designe: "chaque abeille" }, { mot: "elle", ligne: 4, designe: "la reine" }, { mot: "Elles", ligne: 6, designe: "les ouvrières" }, { mot: "ce nectar", ligne: 8, designe: "le nectar des fleurs" }, { mot: "elles", ligne: 10, designe: "les abeilles" }],
    resumes: ["Ce texte explique comment vivent les abeilles dans la ruche et pourquoi elles sont utiles.", "Ce texte raconte l'histoire d'une reine des abeilles qui danse.", "Ce texte explique comment fabriquer du miel à la maison."],
    motInconnu: { mot: "larves", ligne: 6, sens: "les petits qui sortent des œufs, avant de devenir des abeilles", indice: "La reine pond les œufs ; les ouvrières nourrissent les larves.", leurres: ["les fleurs où vont les abeilles", "les gardiennes de la ruche"] },
  }),
  T({
    id: "pateasel", classe: "CE1", type: "prescriptif", titre: "Fabriquer de la pâte à sel",
    lignes: [
      "Matériel :",
      "un grand bol, une cuillère, un verre doseur.",
      "Ingrédients :",
      "deux verres de farine, un verre de sel fin,",
      "un verre d'eau tiède.",
      "Étapes :",
      "1. Verse la farine et le sel dans le bol.",
      "2. Mélange-les avec la cuillère.",
      "3. Ajoute l'eau petit à petit, sans cesser de remuer.",
      "4. Pétris la pâte avec les mains pendant cinq minutes.",
      "Elle doit être souple et ne plus coller aux doigts.",
      "5. Façonne des formes : des perles, des animaux, des fleurs.",
      "6. Laisse sécher tes objets deux jours.",
      "Conseil : si la pâte colle, ajoute un peu de farine ;",
      "si elle s'émiette, ajoute un peu d'eau.",
    ],
    questions: [
      { q: "Qu'est-ce que ce texte apprend à fabriquer ?", r: "De la pâte à sel.", type: "littérale" },
      { q: "Combien de verres de farine faut-il ?", r: "Deux.", type: "littérale", ligne: 4 },
      { q: "Que désigne « Elle » à la ligne 11 ?", r: "La pâte.", type: "reprise", ligne: 11 },
      { q: "Pourquoi ajoute-t-on l'eau petit à petit ?", r: "Pour que la pâte ne soit pas trop mouillée, et bien mélangée.", type: "inférence", ligne: 9 },
      { q: "Que faire si la pâte colle ?", r: "Ajouter un peu de farine.", type: "littérale", ligne: 14 },
      { q: "À quoi servent les numéros ?", r: "À suivre les étapes dans l'ordre.", type: "inférence" },
    ],
    reprises: [{ mot: "les", ligne: 8, designe: "la farine et le sel" }, { mot: "Elle", ligne: 11, designe: "la pâte" }, { mot: "elle", ligne: 15, designe: "la pâte" }],
    resumes: ["Ce texte explique comment fabriquer de la pâte à sel pour faire des objets.", "Ce texte raconte comment un enfant a fait des perles avec sa grand-mère.", "Ce texte explique comment faire du pain."],
    motInconnu: { mot: "Pétris", ligne: 10, sens: "écrase et retourne la pâte avec les mains", indice: "« avec les mains pendant cinq minutes ».", leurres: ["coupe la pâte avec un couteau", "laisse reposer la pâte"] },
  }),
  T({
    id: "renardeau", classe: "CE1", type: "narratif", titre: "Le renardeau trop curieux",
    lignes: [
      "Dans un terrier, au bord du bois, vivait une famille de renards.",
      "Le plus petit, Roux, était aussi le plus curieux.",
      "Sa mère lui répétait : « Ne t'éloigne jamais du terrier ! »",
      "Un matin, Roux vit un papillon bleu.",
      "Il voulut l'attraper et courut, courut…",
      "Quand il s'arrêta, il ne reconnut plus rien autour de lui.",
      "Les arbres étaient immenses et le soleil avait disparu.",
      "Le renardeau se mit à trembler.",
      "Soudain, il sentit une odeur qu'il connaissait bien.",
      "Il suivit cette odeur, le nez au ras du sol.",
      "Derrière un buisson, sa mère l'attendait.",
      "Elle avait parcouru tout le bois pour le retrouver.",
      "Roux se blottit contre elle.",
      "Ce soir-là, il promit de ne plus partir seul.",
      "Mais il pensait encore au papillon bleu…",
    ],
    questions: [
      { q: "Comment s'appelle le renardeau ?", r: "Roux.", type: "littérale", ligne: 2 },
      { q: "Pourquoi Roux s'éloigne-t-il du terrier ?", r: "Il court après un papillon bleu.", type: "littérale", ligne: 5 },
      { q: "Qui est « le renardeau » à la ligne 8 ?", r: "Roux.", type: "reprise", ligne: 8 },
      { q: "Quelle odeur Roux sent-il ? Comment le devines-tu ?", r: "L'odeur de sa mère : il la retrouve derrière le buisson.", type: "inférence", ligne: 11 },
      { q: "Pourquoi Roux tremble-t-il ?", r: "Il a peur : il est perdu.", type: "inférence", ligne: 8 },
      { q: "Roux a-t-il vraiment oublié le papillon ? Justifie.", r: "Non : « il pensait encore au papillon bleu ».", type: "inférence", ligne: 15 },
    ],
    reprises: [{ mot: "Le plus petit", ligne: 2, designe: "Roux" }, { mot: "lui", ligne: 3, designe: "Roux" }, { mot: "l'", ligne: 5, designe: "le papillon" }, { mot: "Le renardeau", ligne: 8, designe: "Roux" }, { mot: "Elle", ligne: 12, designe: "la mère de Roux" }],
    resumes: ["Roux, un renardeau curieux, se perd en suivant un papillon ; sa mère le retrouve.", "Roux attrape un papillon bleu et le rapporte au terrier.", "La mère de Roux se perd dans le bois, et Roux la retrouve."],
    moments: ["Roux voit un papillon bleu et court après.", "Il ne reconnaît plus rien : il est perdu.", "Il suit une odeur qu'il connaît.", "Il retrouve sa mère derrière un buisson."],
    emotions: [{ qui: "Roux", ligne: 8, emotion: "il a peur", indice: "Le renardeau se mit à trembler." }, { qui: "Roux", ligne: 13, emotion: "il est rassuré", indice: "Roux se blottit contre elle." }],
    motInconnu: { mot: "se blottit", ligne: 13, sens: "se serre tout contre quelqu'un pour être protégé", indice: "Roux vient d'avoir peur et retrouve sa mère.", leurres: ["s'enfuit en courant", "se cache sous les feuilles"] },
  }),
  T({
    id: "volcan", classe: "CE1", type: "informatif", titre: "Les volcans",
    lignes: [
      "Un volcan est une montagne pas comme les autres.",
      "Sous la terre, il fait très chaud :",
      "les roches fondent et forment le magma.",
      "Le magma monte par une cheminée jusqu'au cratère.",
      "Quand il sort du volcan, on l'appelle la lave.",
      "La lave coule sur les pentes comme une rivière de feu.",
      "En refroidissant, elle devient dure comme de la pierre.",
      "Certains volcans projettent aussi des cendres et des fumées.",
      "On dit qu'un volcan est actif quand il peut encore entrer en éruption.",
      "D'autres sont endormis depuis très longtemps.",
      "C'est le cas des volcans d'Auvergne, qui dorment depuis des milliers d'années.",
      "Mais à La Réunion, le piton de la Fournaise",
      "entre souvent en éruption.",
      "Les scientifiques le surveillent sans arrêt",
      "pour prévenir les habitants.",
    ],
    questions: [
      { q: "Comment s'appellent les roches fondues sous la terre ?", r: "Le magma.", type: "littérale", ligne: 3 },
      { q: "Que désigne « l' » à la ligne 5 ?", r: "Le magma.", type: "reprise", ligne: 5 },
      { q: "Que devient la lave quand elle refroidit ?", r: "Elle devient dure comme de la pierre.", type: "littérale", ligne: 7 },
      { q: "Les volcans d'Auvergne sont-ils en éruption aujourd'hui ? Justifie.", r: "Non : ils dorment depuis des milliers d'années.", type: "inférence", ligne: 11 },
      { q: "Pourquoi les scientifiques surveillent-ils le piton de la Fournaise ?", r: "Il entre souvent en éruption : il faut prévenir les habitants.", type: "inférence", ligne: 14 },
      { q: "Qui est « le » à la ligne 14 ?", r: "Le piton de la Fournaise.", type: "reprise", ligne: 14 },
    ],
    reprises: [{ mot: "l'", ligne: 5, designe: "le magma" }, { mot: "elle", ligne: 7, designe: "la lave" }, { mot: "D'autres", ligne: 10, designe: "d'autres volcans" }, { mot: "le", ligne: 14, designe: "le piton de la Fournaise" }],
    resumes: ["Ce texte explique ce qu'est un volcan, d'où vient la lave et pourquoi on surveille certains volcans.", "Ce texte raconte l'éruption d'un volcan en Auvergne.", "Ce texte explique comment les scientifiques fabriquent de la lave."],
    motInconnu: { mot: "éruption", ligne: 9, sens: "le moment où le volcan crache de la lave, des cendres, des fumées", indice: "Un volcan actif peut « entrer en éruption » ; la lave, les cendres et les fumées en sortent.", leurres: ["le moment où le volcan s'endort", "la neige au sommet du volcan"] },
  }),
  T({
    id: "bonnet", classe: "CE1", type: "narratif", titre: "Le bonnet de Zoé",
    lignes: [
      "Ce matin-là, il neigeait sur tout le village.",
      "Zoé enfila son manteau, ses bottes et ses gants,",
      "mais elle ne trouva pas son bonnet à pompon.",
      "Elle chercha sous son lit, dans le placard, derrière le canapé.",
      "Rien ! Pas de bonnet.",
      "« Tant pis, je pars sans lui », dit-elle en ouvrant la porte.",
      "Dehors, ses oreilles devinrent vite rouges et glacées.",
      "Dans la cour de l'école, elle aperçut un bonhomme de neige.",
      "Il avait deux cailloux pour les yeux, une carotte pour le nez…",
      "et, sur la tête, un bonnet à pompon tout bleu !",
      "Zoé reconnut tout de suite le bonnet que sa grand-mère lui avait tricoté.",
      "Son petit frère Hugo arriva en courant, les joues roses.",
      "« Tu as vu mon bonhomme ? Il avait froid à la tête ! »",
      "Zoé éclata de rire et récupéra son bonnet.",
      "Le bonhomme, lui, reçut une vieille casserole en guise de chapeau.",
    ],
    questions: [
      { q: "Que cherche Zoé ?", r: "Son bonnet à pompon.", type: "littérale", ligne: 3 },
      { q: "Que désigne « lui » à la ligne 6 ?", r: "Le bonnet.", type: "reprise", ligne: 6 },
      { q: "Pourquoi les oreilles de Zoé deviennent-elles rouges ?", r: "Elle n'a pas de bonnet et il fait très froid : il neige.", type: "inférence", ligne: 7 },
      { q: "Qui est « Il » à la ligne 9 ?", r: "Le bonhomme de neige.", type: "reprise", ligne: 9 },
      { q: "Qui a pris le bonnet de Zoé ? Comment le sais-tu ?", r: "Hugo, son petit frère : il dit que c'est son bonhomme et qu'il avait froid à la tête.", type: "inférence", ligne: 13 },
      { q: "Que met-on finalement sur la tête du bonhomme ?", r: "Une vieille casserole.", type: "littérale", ligne: 15 },
    ],
    reprises: [{ mot: "elle", ligne: 3, designe: "Zoé" }, { mot: "lui", ligne: 6, designe: "le bonnet" }, { mot: "Il", ligne: 9, designe: "le bonhomme de neige" }, { mot: "Son petit frère", ligne: 12, designe: "Hugo, le petit frère de Zoé" }, { mot: "Le bonhomme", ligne: 15, designe: "le bonhomme de neige" }],
    resumes: ["Zoé ne trouve plus son bonnet : son petit frère l'a mis sur la tête de son bonhomme de neige.", "Zoé perd son bonnet dans la neige et le cherche toute la journée.", "Zoé et Hugo construisent ensemble un bonhomme de neige dans la cour."],
    moments: ["Zoé ne trouve pas son bonnet.", "Elle part à l'école sans bonnet, les oreilles glacées.", "Elle voit son bonnet sur la tête d'un bonhomme de neige.", "Hugo explique, et Zoé récupère son bonnet."],
    emotions: [{ qui: "Zoé", ligne: 6, emotion: "elle est déçue, mais décidée", indice: "Tant pis, je pars sans lui" }, { qui: "Zoé", ligne: 14, emotion: "elle trouve ça drôle", indice: "Zoé éclata de rire" }],
    motInconnu: { mot: "enfila", ligne: 2, sens: "mit sur elle (un vêtement)", indice: "Son manteau, ses bottes et ses gants : des vêtements qu'on met pour sortir.", leurres: ["rangea", "lava"] },
  }),

  // ── CE2 : une vingtaine de lignes ──────────────────────────────────────
  T({
    id: "concours", classe: "CE2", type: "narratif", titre: "Le concours de cerfs-volants",
    lignes: [
      "Chaque année, au début du printemps, le village organise un concours de cerfs-volants.",
      "Cette fois, Adam était bien décidé à gagner.",
      "Pendant des semaines, il avait travaillé dans le garage de son grand-père.",
      "Ensemble, ils avaient taillé de fines baguettes de bambou",
      "et cousu une grande voile rouge et jaune.",
      "Le jour du concours, le ciel était parfaitement bleu,",
      "mais il n'y avait pas un souffle de vent.",
      "Les cerfs-volants retombaient les uns après les autres, comme des oiseaux fatigués.",
      "Adam regardait le sien, posé dans l'herbe, et sentait les larmes lui monter aux yeux.",
      "« Patience, murmura son grand-père. Le vent se lève toujours après midi. »",
      "Les autres concurrents rangeaient déjà leurs affaires.",
      "Vers deux heures, les feuilles des peupliers se mirent à frémir.",
      "Adam se leva d'un bond et courut contre le vent.",
      "Son cerf-volant monta, monta, jusqu'à devenir un petit point de couleur.",
      "Les spectateurs levèrent la tête en applaudissant.",
      "Il était le seul à voler encore quand le jury passa.",
      "Le soir, le président du concours remit une coupe au garçon.",
      "Adam la tendit aussitôt à son grand-père :",
      "« Elle est à nous deux, dit-il. C'est toi qui m'as appris à attendre. »",
      "Le vieil homme sourit sans rien dire.",
    ],
    questions: [
      { q: "Avec qui Adam a-t-il fabriqué son cerf-volant ?", r: "Avec son grand-père.", type: "littérale", ligne: 3 },
      { q: "Quel problème y a-t-il le jour du concours ?", r: "Il n'y a pas de vent.", type: "littérale", ligne: 7 },
      { q: "Que désigne « le sien » à la ligne 9 ?", r: "Le cerf-volant d'Adam.", type: "reprise", ligne: 9 },
      { q: "Que signifie « les feuilles des peupliers se mirent à frémir » ? Qu'annonce ce signe ?", r: "Elles bougent un peu : le vent se lève.", type: "inférence", ligne: 12 },
      { q: "Pourquoi Adam gagne-t-il ?", r: "Les autres ont rangé leurs affaires ; il a attendu le vent, et son cerf-volant est le seul à voler.", type: "inférence", ligne: 16 },
      { q: "Qui est « Le vieil homme » à la ligne 20 ?", r: "Le grand-père d'Adam.", type: "reprise", ligne: 20 },
      { q: "Pourquoi Adam dit-il que la coupe est « à nous deux » ?", r: "Ils ont fabriqué le cerf-volant ensemble, et c'est le grand-père qui lui a appris à attendre.", type: "inférence", ligne: 19 },
    ],
    reprises: [{ mot: "il", ligne: 3, designe: "Adam" }, { mot: "ils", ligne: 4, designe: "Adam et son grand-père" }, { mot: "le sien", ligne: 9, designe: "le cerf-volant d'Adam" }, { mot: "au garçon", ligne: 17, designe: "Adam" }, { mot: "la", ligne: 18, designe: "la coupe" }, { mot: "Le vieil homme", ligne: 20, designe: "le grand-père" }],
    resumes: ["Adam et son grand-père ont fabriqué un cerf-volant ; Adam gagne le concours parce qu'il a su attendre le vent.", "Adam perd le concours parce qu'il n'y a pas de vent, mais son grand-père le console.", "Le grand-père d'Adam gagne le concours de cerfs-volants du village."],
    moments: ["Adam et son grand-père fabriquent un cerf-volant.", "Le jour du concours, il n'y a pas de vent.", "Vers deux heures, le vent se lève et le cerf-volant d'Adam monte très haut.", "Adam reçoit la coupe et l'offre à son grand-père."],
    emotions: [{ qui: "Adam", ligne: 9, emotion: "il est triste, déçu", indice: "sentait les larmes lui monter aux yeux" }, { qui: "Adam", ligne: 19, emotion: "il est fier et reconnaissant envers son grand-père", indice: "Elle est à nous deux" }],
    motInconnu: { mot: "concurrents", ligne: 11, sens: "ceux qui participent au concours pour le gagner", indice: "Ils rangent leurs affaires, comme Adam qui veut gagner.", leurres: ["les spectateurs qui regardent", "les membres du jury"] },
  }),
  T({
    id: "migrations", classe: "CE2", type: "informatif", titre: "Le grand voyage des hirondelles",
    lignes: [
      "Chaque automne, des millions d'oiseaux quittent l'Europe pour l'Afrique.",
      "C'est ce qu'on appelle la migration.",
      "Les hirondelles font partie de ces grands voyageurs.",
      "Elles se nourrissent d'insectes qu'elles attrapent en vol.",
      "Or, en hiver, il fait trop froid chez nous : les insectes disparaissent.",
      "Les hirondelles partent donc vers le sud, où la nourriture ne manque pas.",
      "Leur voyage dure plusieurs semaines.",
      "Elles parcourent parfois plus de dix mille kilomètres !",
      "Pour se repérer, elles utilisent le soleil, les étoiles",
      "et peut-être même le champ magnétique de la Terre.",
      "Pendant le trajet, elles doivent traverser la mer Méditerranée",
      "puis le désert du Sahara.",
      "Beaucoup d'entre elles meurent de fatigue ou de faim.",
      "Au printemps, les survivantes reviennent en Europe.",
      "Étonnamment, elles retrouvent souvent le nid qu'elles avaient quitté.",
      "Elles le réparent avec de la boue et des brins d'herbe.",
      "Puis la femelle y pond ses œufs.",
      "En France, on dit qu'une hirondelle ne fait pas le printemps :",
      "il faut en voir beaucoup revenir pour être sûr que l'hiver est fini.",
      "Aujourd'hui, les hirondelles sont protégées, car elles sont de moins en moins nombreuses.",
    ],
    questions: [
      { q: "Comment appelle-t-on le grand voyage des oiseaux ?", r: "La migration.", type: "littérale", ligne: 2 },
      { q: "Pourquoi les hirondelles partent-elles en automne ?", r: "En hiver, les insectes qu'elles mangent disparaissent.", type: "inférence", ligne: 5 },
      { q: "Que désigne « Elles » à la ligne 4 ?", r: "Les hirondelles.", type: "reprise", ligne: 4 },
      { q: "Quels dangers rencontrent-elles pendant le voyage ?", r: "La mer, le désert, la fatigue et la faim.", type: "littérale", ligne: 13 },
      { q: "Que désigne « le » à la ligne 16 ?", r: "Le nid.", type: "reprise", ligne: 16 },
      { q: "Pourquoi « une hirondelle ne fait pas le printemps » ?", r: "Une seule hirondelle ne suffit pas à prouver que l'hiver est fini : il faut en voir beaucoup.", type: "inférence", ligne: 19 },
      { q: "Pourquoi protège-t-on les hirondelles ?", r: "Elles sont de moins en moins nombreuses.", type: "littérale", ligne: 20 },
    ],
    reprises: [{ mot: "ces grands voyageurs", ligne: 3, designe: "les oiseaux qui migrent" }, { mot: "Elles", ligne: 4, designe: "les hirondelles" }, { mot: "les survivantes", ligne: 14, designe: "les hirondelles qui n'ont pas péri" }, { mot: "le", ligne: 16, designe: "le nid" }, { mot: "y", ligne: 17, designe: "dans le nid" }],
    resumes: ["Ce texte explique pourquoi et comment les hirondelles partent en Afrique chaque automne, puis reviennent au printemps.", "Ce texte raconte le voyage d'une hirondelle qui se perd dans le désert.", "Ce texte explique comment construire un nid pour les hirondelles."],
    motInconnu: { mot: "survivantes", ligne: 14, sens: "celles qui sont restées en vie", indice: "Juste avant : « Beaucoup d'entre elles meurent de fatigue ou de faim. »", leurres: ["les plus jeunes", "celles qui sont restées en Afrique"] },
  }),
  T({
    id: "regle-jeu", classe: "CE2", type: "prescriptif", titre: "La course aux trésors",
    lignes: [
      "But du jeu : rapporter plus de trésors que l'équipe adverse.",
      "Nombre de joueurs : deux équipes de quatre à six enfants.",
      "Matériel : six trésors, dont un petit coffre, une carte de la cour, deux cerceaux, un sifflet.",
      "Préparation",
      "L'arbitre cache les six trésors dans la cour.",
      "Il dessine sur la carte une croix à l'emplacement de chacun d'eux.",
      "Il donne une copie de la carte à chaque équipe.",
      "Déroulement",
      "Au coup de sifflet, chaque équipe consulte sa carte.",
      "Un seul joueur à la fois part chercher un trésor.",
      "Quand il revient, il touche la main d'un équipier, qui part à son tour.",
      "Un trésor rapporté est posé dans le cerceau de l'équipe.",
      "Il est interdit de prendre un trésor dans le cerceau des adversaires.",
      "Il est interdit de déplacer un trésor qu'on ne rapporte pas.",
      "Fin de la partie",
      "La partie s'arrête quand tous les trésors ont été rapportés.",
      "L'équipe qui en a le plus a gagné.",
      "En cas d'égalité, on compte les points :",
      "trois points pour le coffre, un point pour chacun des autres trésors.",
      "Conseil : observez bien la carte avant de partir !",
    ],
    questions: [
      { q: "Quel est le but du jeu ?", r: "Rapporter plus de trésors que l'équipe adverse.", type: "littérale", ligne: 1 },
      { q: "Qui cache les trésors ?", r: "L'arbitre.", type: "littérale", ligne: 5 },
      { q: "Que désigne « chacun d'eux » à la ligne 6 ?", r: "Chacun des six trésors.", type: "reprise", ligne: 6 },
      { q: "Combien de joueurs d'une équipe cherchent en même temps ?", r: "Un seul.", type: "littérale", ligne: 10 },
      { q: "Pourquoi ce texte a-t-il des titres (Préparation, Déroulement…) ?", r: "Pour retrouver vite chaque partie de la règle : c'est un texte prescriptif.", type: "inférence" },
      { q: "Chaque équipe a rapporté trois trésors. Qui a gagné ? Explique.", r: "L'équipe qui a le coffre : elle a 3 + 1 + 1 = 5 points, l'autre 3.", type: "inférence", ligne: 19 },
      { q: "Pourquoi est-il conseillé d'observer la carte avant de partir ?", r: "Pour trouver le trésor plus vite et faire gagner du temps à l'équipe.", type: "inférence", ligne: 20 },
    ],
    reprises: [{ mot: "Il", ligne: 6, designe: "l'arbitre" }, { mot: "chacun d'eux", ligne: 6, designe: "chacun des trésors" }, { mot: "il", ligne: 11, designe: "le joueur parti chercher un trésor" }, { mot: "en", ligne: 17, designe: "des trésors" }],
    resumes: ["Ce texte donne les règles d'un jeu d'équipe : il faut rapporter les trésors cachés dans la cour.", "Ce texte raconte une course aux trésors pendant la récréation.", "Ce texte explique comment dessiner la carte d'une cour d'école."],
    motInconnu: { mot: "adversaires", ligne: 13, sens: "les joueurs de l'autre équipe, contre qui l'on joue", indice: "On ne doit pas prendre dans leur cerceau.", leurres: ["les joueurs de son équipe", "les arbitres"] },
  }),
  T({
    id: "poeme-pluie", classe: "CE2", type: "poétique", titre: "Il pleut sur la ville",
    lignes: [
      "Il pleut sur la ville grise,",
      "Il pleut sur les toits pointus,",
      "Les gouttes dansent sur l'église",
      "Et chantent au creux des rues.",
      "",
      "Les parapluies fleurissent",
      "Comme des champignons noirs,",
      "Les gouttières s'emplissent",
      "Et jouent du tambour le soir.",
      "",
      "Le chat, derrière la vitre,",
      "Regarde tomber l'eau ;",
      "Il fait le gros dos, le pitre,",
      "Il préfère son coin chaud.",
      "",
      "Mais demain, quand l'arc-en-ciel",
      "Ouvrira ses sept couleurs,",
      "La ville, lavée de ciel,",
      "Sentira bon comme une fleur.",
    ],
    questions: [
      { q: "De quel temps parle ce poème ?", r: "De la pluie.", type: "littérale", ligne: 1 },
      { q: "À quoi le poète compare-t-il les parapluies ?", r: "À des champignons noirs.", type: "littérale", ligne: 6 },
      { q: "Qui est « Il » à la ligne 11 ?", r: "Le chat.", type: "reprise", ligne: 11 },
      { q: "Que veut dire « les gouttières […] jouent du tambour » ?", r: "L'eau qui tombe dans les gouttières fait du bruit, comme un tambour.", type: "inférence", ligne: 8 },
      { q: "Que va-t-il se passer demain ? Quel mot te le dit ?", r: "La pluie va s'arrêter et le soleil revenir : « l'arc-en-ciel ».", type: "inférence", ligne: 13 },
      { q: "Quels mots riment avec « grise » et « pointus » ?", r: "« église » et « rues ».", type: "littérale", ligne: 3 },
    ],
    reprises: [{ mot: "Il", ligne: 11, designe: "le chat" }, { mot: "ses sept couleurs", ligne: 14, designe: "les couleurs de l'arc-en-ciel" }],
    resumes: ["Le poème décrit la ville sous la pluie et annonce le beau temps du lendemain.", "Le poème raconte l'histoire d'un chat qui se perd sous la pluie.", "Le poème explique comment se forme un arc-en-ciel."],
    motInconnu: { mot: "le pitre", ligne: 11, sens: "le clown, celui qui fait rire en faisant des grimaces", indice: "Le chat « fait le gros dos » : il fait le malin.", leurres: ["le chat qui dort", "celui qui a peur de l'eau"] },
  }),
  T({
    id: "theatre", classe: "CE2", type: "théâtral", titre: "Le roi qui ne voulait pas se coucher",
    lignes: [
      "Personnages : LE ROI, LA REINE, LE GARDE.",
      "(Dans la chambre du château. Il est très tard. Le roi joue aux cartes, seul.)",
      "LA REINE, en bâillant. — Votre Majesté, il est minuit passé.",
      "LE ROI. — Et alors ? Un roi se couche quand il veut !",
      "LA REINE. — Demain, vous recevez l'ambassadeur du pays voisin.",
      "LE ROI, sans lever les yeux. — Il attendra.",
      "(Entre le garde, une bougie à la main.)",
      "LE GARDE. — Majesté, tout le château dort. Les cuisiniers, les musiciens, les chevaux…",
      "LE ROI. — Eh bien, réveillez-les ! J'ai envie d'une fête.",
      "LA REINE, à voix basse, au garde. — Éteignez donc les bougies une à une…",
      "(Le garde souffle une bougie, puis une autre. La pièce s'assombrit.)",
      "LE ROI, plissant les yeux. — Tiens, on n'y voit plus rien. Je ne trouve plus mes cartes.",
      "LA REINE. — C'est sans doute que la nuit est tombée, Majesté.",
      "LE ROI, s'étirant. — Hum… Une petite fête demain, peut-être.",
      "(Il bâille longuement.)",
      "LE ROI. — Je vais seulement fermer les yeux un instant.",
      "(Il s'endort sur sa chaise. La reine et le garde se regardent en souriant.)",
      "LE GARDE, chuchotant. — Bonne nuit, Majesté.",
      "LA REINE, chuchotant aussi. — Et surtout, ne faites pas de bruit…",
      "(Rideau.)",
    ],
    questions: [
      { q: "Qui sont les personnages ?", r: "Le roi, la reine, le garde.", type: "littérale", ligne: 1 },
      { q: "À quoi servent les phrases entre parenthèses ?", r: "Elles disent où l'on est, ce que font les personnages et comment ils parlent : ce sont les didascalies.", type: "inférence", ligne: 2 },
      { q: "Pourquoi la reine fait-elle éteindre les bougies ?", r: "Pour que le roi croie qu'il fait nuit et qu'il ait envie de dormir.", type: "inférence", ligne: 10 },
      { q: "Qui est « Il » à la ligne 6 ?", r: "L'ambassadeur du pays voisin.", type: "reprise", ligne: 6 },
      { q: "Comment le garde et la reine parlent-ils à la fin ? Pourquoi ?", r: "En chuchotant, pour ne pas réveiller le roi.", type: "inférence", ligne: 18 },
      { q: "La ruse de la reine a-t-elle réussi ? Justifie.", r: "Oui : le roi s'endort sur sa chaise.", type: "inférence", ligne: 17 },
    ],
    reprises: [{ mot: "Votre Majesté", ligne: 3, designe: "le roi" }, { mot: "Il", ligne: 6, designe: "l'ambassadeur" }, { mot: "les", ligne: 9, designe: "les cuisiniers, les musiciens, les chevaux" }, { mot: "Il", ligne: 15, designe: "le roi" }],
    resumes: ["Le roi ne veut pas se coucher ; la reine fait éteindre les bougies, et il finit par s'endormir.", "Le roi organise une grande fête au château pour l'ambassadeur.", "Le garde éteint les bougies parce que la reine a peur du noir."],
    moments: ["Il est minuit passé, et le roi joue aux cartes.", "Le roi veut qu'on réveille tout le château pour une fête.", "Le garde éteint les bougies une à une.", "Le roi s'endort sur sa chaise."],
    emotions: [{ qui: "le roi", ligne: 4, emotion: "il est têtu, agacé", indice: "Un roi se couche quand il veut !" }, { qui: "la reine et le garde", ligne: 17, emotion: "ils sont amusés et soulagés", indice: "se regardent en souriant" }],
    motInconnu: { mot: "ambassadeur", ligne: 5, sens: "celui qui représente son pays auprès d'un autre pays", indice: "Il vient « du pays voisin » et le roi doit le recevoir.", leurres: ["le cuisinier du roi", "le garde du château"] },
  }),
  T({
    id: "loup-ce2", classe: "CE2", type: "narratif", titre: "Le loup qui avait peur du noir",
    lignes: [
      "Au fond de la forêt vivait un loup que tous les animaux craignaient.",
      "Ses crocs étaient longs, son pelage noir comme la nuit, et son hurlement glaçait le sang.",
      "Pourtant, ce loup avait un secret que personne ne connaissait :",
      "dès que le soleil se couchait, il tremblait de peur.",
      "Chaque soir, il allumait en cachette une petite lanterne au fond de sa tanière.",
      "Une nuit, un coup de vent souffla la flamme.",
      "Le grand loup poussa un cri si aigu qu'on aurait dit celui d'un louveteau.",
      "Une petite chouette, posée sur une branche, l'entendit.",
      "Elle descendit et se posa près de l'entrée de la tanière.",
      "« Qui pleure ainsi ? » demanda-t-elle.",
      "Le loup, honteux, avoua tout.",
      "La chouette ne se moqua pas de lui.",
      "« Moi, je vois dans le noir, dit-elle. Je pourrais te montrer la beauté de la nuit. »",
      "Toute la nuit, elle lui parla des étoiles, des lucioles, du chant du grillon.",
      "Peu à peu, l'animal se calma.",
      "Il découvrit que la nuit n'était pas seulement noire :",
      "elle brillait de mille petites lumières.",
      "Depuis ce jour, on voit souvent un loup et une chouette",
      "assis côte à côte, regardant le ciel.",
      "Et la lanterne ? Le loup l'a donnée à un hérisson qui avait, lui aussi, peur du noir.",
    ],
    questions: [
      { q: "Quel est le secret du loup ?", r: "Il a peur du noir.", type: "littérale", ligne: 4 },
      { q: "Pourquoi le loup pousse-t-il un cri ?", r: "Le vent a éteint la lanterne : il se retrouve dans le noir.", type: "inférence", ligne: 6 },
      { q: "Que désigne « l' » à la ligne 8 ?", r: "Le loup (son cri).", type: "reprise", ligne: 8 },
      { q: "Qui est « l'animal » à la ligne 15 ?", r: "Le loup.", type: "reprise", ligne: 15 },
      { q: "Pourquoi le loup est-il « honteux » ?", r: "Un loup qui fait peur à tous a peur du noir : il a honte qu'on le sache.", type: "inférence", ligne: 11 },
      { q: "Comment la chouette aide-t-elle le loup ?", r: "Elle lui montre les belles choses de la nuit : les étoiles, les lucioles, le grillon.", type: "littérale", ligne: 14 },
      { q: "Pourquoi le loup donne-t-il sa lanterne au hérisson ?", r: "Il n'en a plus besoin, et le hérisson a peur du noir comme lui avant.", type: "inférence", ligne: 20 },
    ],
    reprises: [{ mot: "ce loup", ligne: 3, designe: "le loup de la forêt" }, { mot: "l'", ligne: 8, designe: "le loup" }, { mot: "Elle", ligne: 9, designe: "la chouette" }, { mot: "lui", ligne: 12, designe: "le loup" }, { mot: "l'animal", ligne: 15, designe: "le loup" }, { mot: "l'", ligne: 20, designe: "la lanterne" }],
    resumes: ["Un loup qui a peur du noir découvre, grâce à une chouette, que la nuit est belle.", "Une chouette a peur du noir, et un loup lui prête sa lanterne.", "Un loup méchant fait peur, la nuit, à tous les animaux de la forêt."],
    moments: ["Le loup allume chaque soir une lanterne en cachette.", "Un coup de vent éteint la flamme, et le loup crie.", "La chouette lui montre les beautés de la nuit.", "Le loup donne sa lanterne à un hérisson."],
    emotions: [{ qui: "le loup", ligne: 11, emotion: "il a honte", indice: "Le loup, honteux, avoua tout." }, { qui: "le loup", ligne: 15, emotion: "il se calme, il n'a plus peur", indice: "Peu à peu, l'animal se calma." }],
    motInconnu: { mot: "tanière", ligne: 5, sens: "l'abri, le trou où vit un animal sauvage", indice: "Le loup y allume sa lanterne ; la chouette se pose à l'entrée.", leurres: ["la cime d'un arbre", "une lanterne"] },
  }),
  T({
    id: "grenier", classe: "CE2", type: "narratif", titre: "Le secret du grenier",
    lignes: [
      "Depuis qu'ils avaient emménagé dans la vieille maison, Lucas entendait des bruits étranges.",
      "Chaque nuit, vers minuit, quelque chose grattait au-dessus de sa chambre.",
      "Gratt, gratt, gratt… puis un petit trottinement, et plus rien.",
      "Ses parents haussaient les épaules : « C'est le vent dans les tuiles. »",
      "Mais Lucas, lui, n'y croyait pas du tout.",
      "Un samedi, il prit sa lampe de poche et monta l'escalier du grenier.",
      "La porte grinça. L'air sentait la poussière et le vieux papier.",
      "Dans un coin, sous une malle, il remarqua de petits morceaux de journal déchirés.",
      "Il s'approcha sans faire de bruit et souleva doucement le couvercle.",
      "Quatre minuscules boules de poils dormaient, serrées les unes contre les autres.",
      "Une ombre fila soudain entre ses jambes : c'était la mère, inquiète pour ses petits.",
      "Lucas recula aussitôt et referma la malle avec précaution.",
      "Il redescendit l'escalier, le cœur battant, et ne dit rien à personne.",
      "Les jours suivants, il monta chaque soir une soucoupe d'eau et quelques miettes de fromage.",
      "Ses parents s'étonnaient de voir le fromage disparaître si vite.",
      "Un mois plus tard, quatre souriceaux trottinaient dans tout le grenier.",
      "Lucas comprit qu'il ne pourrait pas garder son secret bien longtemps.",
      "Il emmena son père au grenier et lui montra la petite famille.",
      "Son père sourit : « Le vent dans les tuiles, hein ? »",
      "Le dimanche suivant, ils installèrent ensemble la famille souris dans la cabane du jardin.",
    ],
    questions: [
      { q: "Qu'entend Lucas chaque nuit ?", r: "Quelque chose qui gratte au-dessus de sa chambre, puis un petit trottinement.", type: "littérale", ligne: 2 },
      { q: "Que pensent ses parents ? Lucas est-il d'accord ?", r: "Que c'est le vent dans les tuiles ; non, Lucas n'y croit pas.", type: "littérale", ligne: 5 },
      { q: "Qui sont les « quatre minuscules boules de poils » de la ligne 10 ?", r: "Des bébés souris, des souriceaux.", type: "reprise", ligne: 10 },
      { q: "Pourquoi Lucas ne dit-il rien à personne ?", r: "Il veut protéger les souris : ses parents pourraient vouloir s'en débarrasser.", type: "inférence", ligne: 13 },
      { q: "Pourquoi le fromage disparaît-il si vite ?", r: "Lucas en monte chaque soir pour nourrir les souris.", type: "inférence", ligne: 15 },
      { q: "Que désigne « la petite famille » à la ligne 18 ?", r: "La mère souris et ses quatre souriceaux.", type: "reprise", ligne: 18 },
      { q: "Pourquoi le père dit-il : « Le vent dans les tuiles, hein ? »", r: "Il plaisante : ce n'était pas le vent, mais des souris ; Lucas avait raison.", type: "inférence", ligne: 19 },
    ],
    reprises: [{ mot: "lui", ligne: 5, designe: "Lucas" }, { mot: "il", ligne: 6, designe: "Lucas" }, { mot: "Quatre minuscules boules de poils", ligne: 10, designe: "les souriceaux" }, { mot: "la mère", ligne: 11, designe: "la mère souris" }, { mot: "la petite famille", ligne: 18, designe: "la mère souris et ses petits" }, { mot: "ils", ligne: 20, designe: "Lucas et son père" }],
    resumes: ["Lucas découvre une famille de souris au grenier, la nourrit en secret, puis l'installe avec son père dans la cabane du jardin.", "Lucas a peur des bruits du grenier et refuse d'y monter.", "Les parents de Lucas trouvent des souris au grenier et veulent s'en débarrasser."],
    moments: ["Lucas entend chaque nuit des bruits au grenier.", "Il monte au grenier et découvre une famille de souris.", "Il la nourrit en secret pendant un mois.", "Avec son père, il installe les souris dans la cabane du jardin."],
    emotions: [{ qui: "Lucas", ligne: 13, emotion: "il est ému, il a eu peur, il garde son secret", indice: "le cœur battant" }, { qui: "le père", ligne: 19, emotion: "il est amusé, complice", indice: "Son père sourit" }],
    motInconnu: { mot: "souriceaux", ligne: 16, sens: "les petits de la souris", indice: "On entend « souris » dans le mot ; ce sont les quatre petits de la ligne 10.", leurres: ["des chats", "des oiseaux"] },
  }),
];

/** Les lignes du texte avec leur numéro ; une ligne vide, entre deux strophes, n'en a pas. */
export function lignesNumerotees(t: TexteAComprendre): { n: number | null; texte: string }[] {
  let n = 0;
  return t.lignes.map((texte) => (texte.trim() ? { n: ++n, texte } : { n: null, texte }));
}

/** La ligne numéro n (à partir de 1), sans compter les lignes vides. */
export const ligneDe = (t: TexteAComprendre, n: number) => t.lignes.filter((l) => l.trim())[n - 1] ?? "";

export const textesDeLaClasse = (classe: Classe) => TEXTES.filter((t) => t.classe === classe);
export const texteDe = (id: string) => TEXTES.find((t) => t.id === id);
